
logging:
    level:
#        root: warn
#        org:
#            springframework: trace
        com:
            gome:
                o2m:
                    swagger: warn
    file: /tmp/swagger/swagger_demo.log

#数据库配置
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=false
        driverClassName: com.mysql.jdbc.Driver
        name: test
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#swagger配置
application:
    swagger:
        title: swagger测试系统
        version: 1.0.0
        description: springboot 集成 swagger测试系统
        contact: moben
        license: The Apache License, Version 2.0
        license-url: http://www.apache.org/licenses/LICENSE-2.0.html

#tomcat服务端口配置
server:
    port: 80

#mybatis配置
mybatis:
    type-aliases-package: com.gome.o2m.swagger.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.gome.o2m.swagger.base.ReadMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql